cont_common = {
    "ain't": "am not",
    "aren't": "are not",
    "can't": "cannot",
    "can't've": "cannot have",
    "Ain't": "Am not",
    "Aren't": "Are not",
    "Can't": "Cannot",
    "Can't've": "Cannot have",
    " 'cause": " because",
    "could've": "could have",
    "couldn't": "could not",
    "couldn't've": "could not have",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",
    "Didn't": "Did not",
    "Doesn't": "Does not",
    "Don't": "Do not",
    "hadn't": "had not",
    "hadn't've": "had not have",
    "hasn't": "has not",
    "haven't": "have not",
    "he'd": "he had",
    "he'd've": "he would have",
    "he'll": "he will",
    "he'll've": "he will have",
    "he's": "he is",
    "He'd": "He had",
    "He'd've": "He would have",
    "He'll": "He will",
    "He'll've": "He will have",
    "He's": "He is",
    "how'd": "how did",
    "how'd'y": "how do you",
    "how'll": "how will",
    "how's": "how is",
    "How'd": "How did",
    "How'd'y": "How do you",
    "How'll": "How will",
    "How's": "How is",
    "i'd": "I had",
    "i'd've": "I would have",
    "i'll": "I will",
    "i'll've": "I will have",
    "i'm": "I am",
    "i've": "I have",
    "isn't": "is not",
    "it'd": "it had",
    "it'd've": "it would have",
    "it'll": "it will",
    "it'll've": "it will have",
    "it's": "it is",
    "I'd": "I had",
    "I'd've": "I would have",
    "I'll": "I will",
    "I'll've": "I will have",
    "I'm": "I am",
    "I've": "I have",
    "It'd": "It had",
    "It'd've": "It would have",
    "It'll": "It will",
    "It'll've": "It will have",
    "It's": "It is",
    "Let's": "Let us",
    "let's": "let us",
    "ma'am": "madam",
    "Ma'am": "Madam",
    "mayn't": "may not",
    "might've": "might have",
    "mightn't": "might not",
    "mightn't've": "might not have",
    "must've": "must have",
    "mustn't": "must not",
    "mustn't've": "must not have",
    "needn't": "need not",
    "needn't've": "need not have",
    "o'clock": "of the clock",
    "O'clock": "Of the clock",
    "oughtn't": "ought not",
    "oughtn't've": "ought not have",
    "shan't": "shall not",
    "sha'n't": "shall not",
    "shan't've": "shall not have",
    "she'd": "she had",
    "she'd've": "she would have",
    "she'll": "she will",
    "she'll've": "she will have",
    "she's": "she is",
    "She'd": "She had",
    "She'd've": "She would have",
    "She'll": "She will",
    "She'll've": "She will have",
    "She's": "She is",
    "should've": "should have",
    "shouldn't": "should not",
    "shouldn't've": "should not have",
    "so've": "so have",
    "so's": "so is",
    "that'd": "that had",
    "that'd've": "that would have",
    "that's": "that is",
    "there'd": "there had",
    "there'd've": "there would have",
    "there's": "there is",
    "they'd": "they had",
    "they'd've": "they would have",
    "they'll": "they will",
    "they'll've": "they will have",
    "they're": "they are",
    "they've": "they have",
    "That'd": "That had",
    "That'd've": "That would have",
    "That's": "That is",
    "There'd": "There had",
    "There'd've": "There would have",
    "There's": "There is",
    "They'd": "They had",
    "They'd've": "They would have",
    "They'll": "They will",
    "They'll've": "They will have",
    "They're": "They are",
    "They've": "They have",
    "to've": "to have",
    "wasn't": "was not",
    "we'd": "we had",
    "we'd've": "we would have",
    "we'll": "we will",
    "we'll've": "we will have",
    "we're": "we are",
    "we've": "we have",
    "We'd": "We had",
    "We'd've": "We would have",
    "We'll": "We will",
    "We'll've": "We will have",
    "We're": "We are",
    "We've": "We have",
    "weren't": "were not",
    "what'll": "what will",
    "what'll've": "what will have",
    "what're": "what are",
    "what's": "what is",
    "what've": "what have",
    "when's": "when is",
    "when've": "when have",
    "What'll": "What will",
    "What'll've": "What will have",
    "What're": "What are",
    "What's": "What is",
    "What've": "What have",
    "When's": "When is",
    "When've": "When have",
    "where'd": "where did",
    "where's": "where is",
    "where've": "where have",
    "who'll": "who will",
    "who'll've": "who will have",
    "who's": "who is",
    "who've": "who have",
    "why's": "why is",
    "why've": "why have",
    "Who'll": "Who will",
    "Who'll've": "Who will have",
    "Who's": "Who is",
    "Who've": "Who have",
    "Why's": "Why is",
    "Why've": "Why have",
    "will've": "will have",
    "won't": "will not",
    "won't've": "will not have",
    "would've": "would have",
    "wouldn't": "would not",
    "Wouldn't": "would not",
    "wouldn't've": "would not have",
    "y'all": "you all",
    "y'all'd": "you all would",
    "y'all'd've": "you all would have",
    "y'all're": "you all are",
    "y'all've": "you all have",
    "you'd": "you had",
    "you'd've": "you would have",
    "you'll": "you will",
    "you'll've": "you will have",
    "you're": "you are",
    "you've": "you have",
    "Y'all": "You all",
    "Y'all'd": "You all would",
    "Y'all'd've": "You all would have",
    "Y'all're": "You all are",
    "Y'all've": "You all have",
    "You'd": "You had",
    "You'd've": "You would have",
    "You'll": "You will",
    "You'll've": "You will have",
    "You're": "You are",
    "You've": "You have"
}

cont_time = {
    "mins": "minutes",
    "min": "minute",
    "hrs": "hours",
    "hr": "hour",
    "yr": "year",
    "yrs": "years",
    "sec": "seconds"
}

cont_abbreviations = {
    "xmax": "christmas",
    "x-max": "christmas",
    "X-max": "Christmas",
    "&": "and",
    "omg": "oh my god",
    "imo": "imy opinion",
    "btw": "by the way",
    "idk": "I do not know",
    "tbh": "to be honest",
    "fyi": "for you information",
    "thx": "thanks",
    "sry": "sorry",
    "ty": "thank you",
    "imho": "in my honest opinion",
    "idek": "I do not even known",
    "e.g.": "for example",
    "etc": "and other things",
    "i.e.": "that is",
    "ad": "advertisement",
    "ads": "advertisements",
    "bc": "because"
}

language_corpus = (
    'italiano', 'italiana', 'arabic', 'russian',
    'french', 'francais', 'français', 'german',
    'dutch', 'italian', 'chinese', 'persian',
    'deutsch', 'русский', '中国人', 'عربي',
    'nederlands', 'portuguese', 'português'
)
